import Head from 'next/head'
import ActionButton from '../components/ActionButton'
import InputButton from '../components/InputButton'
import Map from '../components/Map'
import Profile from '../components/Profile'



const styles={
  wrapper:`flex flex-col h-screen`
}

export default function Home() {
   
  
     
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>UBER CLONE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
                <Map/>
     
        <Profile/>
        <ActionButton/>
        <InputButton/>
    </div>
  )
}
